### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by FSajadi** [zmartzone/liboauth2#1]
I want to use this library for OAuth, it would be good if there is a sample/reference/and so on.
Regards

**Comment by zandbelt** [comment]
agreed; as this is a fairly new development, I have not spent time on that yet; can you explain what you're looking to build with it? perhaps I can then guide you and provide some docs at the same time

**Comment by FSajadi** [comment]
I want to have access to all OAUTH2 based accounts (like Gmail ) by using this library.

**Comment by zandbelt** [comment]
are you writing an application in the C programming language?

**Comment by FSajadi** [comment]
Yes I'm using c/cpp in Linux.

**Comment by zandbelt** [comment]
Which grant type do you want to use?

**Comment by FSajadi** [comment]
For now the `refresh_token` and `authorization_code`

**Comment by zandbelt** [comment]
how would you handle the user-agent/browser part that is required for the authorization code grant type from your C app?

**Comment by FSajadi** [comment]
In these steps, a url should be open manually by user. The C app should inform the user for opening the url.

**Comment by zandbelt** [comment]
so far the library has not been extended for that use case; that will only be added later this year

**Comment by FSajadi** [comment]
Ok, can you please describe how you perform OAuth2 in current version/release?

**Comment by zandbelt** [comment]
there's only Resource Server functionality, no toplevel Client functionality yet

**Comment by FSajadi** [comment]
A fundamental question is that, why we should use the library for OAuth2? We can do them with `curl` very simply. Is it right?

**Comment by lukehinds** [comment]
hi @zandbelt 

> there's only Resource Server functionality, no toplevel Client functionality yet

Is this still the case?

**Comment by zandbelt** [comment]
> hi @zandbelt
> 
> > there's only Resource Server functionality, no toplevel Client functionality yet
> 
> Is this still the case?

what are you looking for exactly?

**Comment by lukehinds** [comment]
> > hi @zandbelt
> > > there's only Resource Server functionality, no toplevel Client functionality yet
> > 
> > 
> > Is this still the case?
> 
> what are you looking for exactly?

I would like to use the client auth flow, a user connects to a OIDC issuer (provides the client_id, secret), server returns a url which client opens in a browser, user grants to a scope , gets an ID token etc

**Comment by zandbelt** [comment]
then no, liboauth2 is still primarily focused on server side functionality

**Comment by lukehinds** [comment]
that is fair enough, I will have a dig around (unless you know of something out there?).

**Comment by zandbelt** [comment]
perhaps https://github.com/babelouest/iddawc
