### ISSUE TITLE
#define statements in config.h can lead to collision with other libraries

### ISSUE THREAD

**Issue by babelouest** [zmartzone/liboauth2#10]
The file `include/oauth2/config.h` generated by autoconf uses non specific `#define` statements, like `#define PACKAGE_NAME`.

As far as I can see, this file is used in `include/oauth2/apache.h` only.

If a program includes liboauth2 and another library with the same type of `config.h` file, the build will probably fail.

A solution is to prefix the `#define` statements in `config.h` to lower the risk of collision. What do you think?

**Comment by zandbelt** [comment]
I think that is kind of expected when using autoconf and I don't think there's even a way to do it differently (and still use authconf), see also https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Configuration-Headers.html

**Comment by babelouest** [comment]
I'm not familiar with autoconf so I've made some tests and it looks like the file config.h isn't even required for the library to work properly.

Here is the changes I've made for my test:

- Remove `AC_CONFIG_HEADERS([include/oauth2/config.h])` from file `configure.ac`
- Remove `config.h*` references from file `Makefile.am`
- Remove `#include <oauth2/config.h>` from the files `include/oauth2/apache.h` and `test/check_version.c`

After these steps, the library builds without any error and the tests are all successful (including memchached and redis tests), because autoconf defines all the config variables during compilation, example:

```
libtool: compile:  gcc -DPACKAGE_NAME=\"liboauth2\" -DPACKAGE_TARNAME=\"liboauth2\" \
-DPACKAGE_VERSION=\"1.3.0\" "-DPACKAGE_STRING=\"liboauth2 1.3.0\"" \
-DPACKAGE_BUGREPORT=\"user@example.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 \
-DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 \
-DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 \
-DLT_OBJDIR=\".libs/\" -I. -Wall -Werror -Iinclude -Isrc -g -O2 -MT src/cache/liboauth2_memcache_la-memcache.lo -MD -MP \
-MF src/cache/.deps/liboauth2_memcache_la-memcache.Tpo -c src/cache/memcache.c  -fPIC -DPIC \
-o src/cache/.libs/liboauth2_memcache_la-memcache.o
```

Don't think I'm trying to convince you to remove the file `config.h` because of my investigation, far from it, it's your project and your call, and I might have missed some important stuff.

But I think it was worth giving you the result of my tests...

**Comment by zandbelt** [comment]
After looking in to it, I believe this was a combination of a leftover from an early experiment plus a way to avoid `ap_auto_config` inclusion errors, so I have removed it now indeed; thanks.
