### ISSUE TITLE
encapsulate oauth2_log_sink_t 

### ISSUE THREAD

**Issue by niyamaka** [zmartzone/liboauth2#2]
Hello,
I'm using this great library in other environment than apache/nginx (https://bitbucket.org/account/user/yuneta/projects/YUNETA). 
I can't update to last version (using version 1.0.0) because encapsulating oauth2_log_sink_t.
Please, can be possible make oauth2_log_sink_t public?
Thanks
Niyamaka

**Comment by zandbelt** [comment]
Generally encapsulation is preferred and I don't think it should be changed back. Why can you not use the encapsulation functions to achieve what you want?

**Comment by niyamaka** [comment]
You are right, sorry, now I'm using:
   priv->oath2_sink = oauth2_log_sink_create(
        OAUTH2_LOG_ERROR, // oauth2_log_level_t level,
        oauth2_log_callback, // oauth2_log_function_t callback,
        gobj  // void *ctx
    );
