### ISSUE TITLE
unaligned memory access on 32-bit ARM when running tests

### ISSUE THREAD

**Issue by abbra** [zmartzone/liboauth2#21]
When building liboauth2 on armv7hl on Fedora Rawhide, I get tests to crash reliably with SIGBUS. ARMv7 is known to be very sensitive to unaligned memory access and Linux kernel issues bus error for these problems.

The following scratch build shows a problem: https://koji.fedoraproject.org/koji/watchlogs?taskID=66315687 (scroll down to the end). Sadly, I don't have 32-bit ARMv7 locally so cannot reproduce these issues myself.

The log of the scratch build will disappear in 14 days or so.

**Comment by zandbelt** [comment]
thanks for reporting; until I'm able to reproduce them myself I don't think I can do a lot; for future reference I'm attaching a copy of the log here
[issue21.log](https://github.com/zmartzone/liboauth2/files/6348989/issue21.log)
