### ISSUE TITLE
fix broken dependency on Debian Buster

### ISSUE THREAD

**Issue by Gedimin** [zmartzone/liboauth2#23]
The package liboauth2_1.4.1-1.bionic+1_amd64.deb has pinned on old package - libhiredis0.13 (>= 0.13.1).
I have already libhiredis0.14 installed on Debian Buster, but it's required only libhiredis0.13.

**Comment by zandbelt** [comment]
you cannot install an Ubuntu Bionic package on a Debian Buster system
