### ISSUE TITLE
unaligned memory access on 64-bit SPARC when running tests

### ISSUE THREAD

**Issue by glenk** [zmartzone/liboauth2#24]
When running make test after building liboauth2 on 64-bit SPARC (niagara4) on Solaris 10 with gcc 5.5.0, several tests dump core with a SIGBUS error.  As SPARC is sensitive to alignment issues, I expect that this is a platform-specific issue.

The test-suite.log output file is attached, along with the 'make test' stdout/stderr output for the test run.
[test-suite.log](https://github.com/zmartzone/liboauth2/files/6529067/test-suite.log)
[gmake_test_out.txt](https://github.com/zmartzone/liboauth2/files/6529072/gmake_test_out.txt)

The stack trace from the final test (test/check_openidc.c:1004:E:core:test_openidc_state_cookie:0:) is attached as gdb_core.txt.  (Unfortunately, the final core file overwrote the previous core files.)   
[gdb_core.txt](https://github.com/zmartzone/liboauth2/files/6529071/gdb_core.txt)

I'm happy to provide any additional information on this issue, and any further assistance to help resolve this.

**Comment by zandbelt** [comment]
unfortunately I don't have access to a SPARC machine so I'm not sure how to address this (yet)

**Comment by zandbelt** [comment]
would you be able to test a branch with a possible fix?

**Comment by glenk** [comment]
Absolutely!  Happy to help.

**Comment by zandbelt** [comment]
could you please try https://github.com/zmartzone/liboauth2/tree/fix-memory-alignment ?

**Comment by glenk** [comment]
Will do!   Pulling it down now, I'll let you know how it goes.

**Comment by glenk** [comment]
Looks much better, runs without generating a core or issuing a SIGBUS error!  Here's the test-suite.log.
[test-suite.log](https://github.com/zmartzone/liboauth2/files/6541253/test-suite.log)
I'll check to see if the tests are failing due to some mis-configuration in my environment.

**Comment by zandbelt** [comment]
ok, that looks good: the remaining error is because you don't run a Redis server, at least not in the setup required to finish the tests succesfully; I'll merge and release 1.4.2

**Comment by glenk** [comment]
Perfect!  Thanks Hans!
