### ISSUE TITLE
About the bug of oauth2_auth_client_secret_jwt

### ISSUE THREAD

**Issue by pengjiaoyang** [zmartzone/liboauth2#3]
func:oauth2_auth_client_secret_jwt
if ((auth->client_secret_jwt.client_id == NULL) ||
	    (auth->client_secret_jwt.jwk == NULL) ||
	    (auth->client_secret_jwt.aud = NULL))
		goto end;
Correction：
auth->client_secret_jwt.aud == NULL
The affected branch is: master and liboauth2-1.1.1,Please check other branches

**Comment by zandbelt** [comment]
I don't follow. Can you provide an actual patch/PR that shows what you'd like to change and why?
