### ISSUE TITLE
dependency error on liboauth2 install

### ISSUE THREAD

**Issue by salpcnsi** [zmartzone/liboauth2#32]
Insttalling liboauth2 on RedHat 8, get following error:

Installing: yum localinstall liboauth2-1.4.4-1.el8.x86_64.rpm

nothing provides pkgconfig(libmemcached) >= 0.8.0 needed by liboauth2-1.4.4-1.el8.x86_64

Though libmemcached is already installed.
rpm -qa | grep libmemcache
libmemcached-1.0.18-15.el8.x86_64
libmemcached-libs-1.0.18-15.el8.x86_64

**Comment by salpcnsi** [comment]
Please ignore.

I had to install libmemcached-devel package to address this error.

**Comment by zandbelt** [comment]
this was actually a longstanding packaging bug in the RPM packages provided in the Releases section; I have corrected that now with 1.4.4-2 RPMs for CentOS/RHEL 7 and 8

**Comment by salpcnsi** [comment]
Thank you for promptly addressing the issue.
I have used oauth2 libraries with great success on redhat 7 but others should not face this issue on redhat 8.
