### ISSUE TITLE
Test fails on a Debian testing (Bookworm) distribution

### ISSUE THREAD

**Issue by babelouest** [zmartzone/liboauth2#33]
The library builds successfully on a Debian Bookworm, using the packages `libmemcached-dev` and `libhiredis-dev`, but the test fail here:

```
test/check_cache.c:60:F:core:test_cache_memcache:0: Assertion 'rc == 1' failed: rc == 0, 1 == 1
test/check_cache.c:60:F:core:test_cache_redis:0: Assertion 'rc == 1' failed: rc == 0, 1 == 1
```

The failing test is the following:

```C
static void _test_basic_cache(oauth2_cache_t *c)
{
	bool rc = false;
	char *value = NULL;

	rc = oauth2_cache_set(_log, c, "piet", "klaas", 2);
	ck_assert_int_eq(rc, true);
```

**Comment by zandbelt** [comment]
that's strange: when I build, package and run tests myself on Debian Bookworm, it succeeds; can you compare with the Dockerfile that I use?
```
FROM debian:bookworm
MAINTAINER hans.zandbelt@zmartzone.eu

RUN apt-get update && apt-get install -y apt-utils wget

RUN echo "Acquire::http::Timeout \"90\";" > /etc/apt/apt.conf.d/99timeout

RUN apt-get update && apt-get install -y build-essential devscripts dh-make pkg-config util-linux
RUN apt-get update && apt-get install -y gcc tar autoconf automake libtool

ENV DEB_BUILD_OPTIONS noddebs

ENV NGINX_VERSION 1.18.0
ENV OAUTH2_VERSION 1.4.4.1

ENV OAUTH2_TGZ liboauth2-${OAUTH2_VERSION}.tar.gz
ENV OAUTH2_ORIG_TGZ liboauth2-${OAUTH2_VERSION}.orig.tar.gz

RUN apt-get update && apt-get install -y libssl-dev libjansson-dev libcurl4-openssl-dev
RUN apt-get update && apt-get install -y libmemcached-dev memcached
RUN apt-get update && apt-get install -y libhiredis-dev redis-server
RUN apt-get update && apt-get install -y apache2-dev vim check

WORKDIR /root

RUN apt-get update && apt-get install -y libghc-regex-pcre-dev zlib1g-dev libxml2-dev libxslt-dev libgd-dev libgeoip-dev
RUN wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && tar zxvf nginx-${NGINX_VERSION}.tar.gz
RUN ln -s nginx-${NGINX_VERSION} nginx

RUN apt-get install -y libcjose-dev

COPY ${OAUTH2_TGZ} ${OAUTH2_ORIG_TGZ}
RUN tar zxvf ${OAUTH2_ORIG_TGZ}

WORKDIR /root/liboauth2-${OAUTH2_VERSION}
ADD debian-liboauth2 debian
RUN sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf

ENV CK_FORK no

RUN cd /root/nginx && ./configure --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-q9LD4J/nginx-${NGINX_VERSION}=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_sub_module

RUN service memcached start && service redis-server start && sleep 1 && dpkg-buildpackage -uc -us
```

**Comment by babelouest** [comment]
Actually, I believe the problem comes from me, in my Debian Bookworm docker instance, I install `libmemcached-dev` and `libhiredis-dev`, but no `redis-server` or `memchached`, if I install them and run the services (as in your Docker file), the test succeeds. My bad!

In your opinion, would it be possible to mock the redis and the memcached servers during the tests?

**Comment by zandbelt** [comment]
> In your opinion, would it be possible to mock the redis and the memcached servers during the tests?

I have the feeling I'd be debugging the mock more than testing the actual code.
How about skipping those tests using an environment variable setting?

**Comment by babelouest** [comment]
>  How about skipping those tests using an environment variable setting?

Sort of, I patched the `check_cache.c` to disable redis and memchache tests, now it works on my side.

Although the package still fails to build on Debian servers: https://buildd.debian.org/status/fetch.php?pkg=liboauth2&arch=amd64&ver=1.4.4.1-2&stamp=1650030750&raw=0

The first test to fail is the `http_server_spawn`:

```
Running suite(s): liboauth2
 version
[test/check_liboauth2.c:271:http_server_spawn:ERR] bind failed
```

If I force this test to fail on my machine, I can reproduce the failing list. So I assume that if I can make the test http server running, the package will build successfully on Debian servers. Now the goal is to find what's wrong. Is it the port number (8888), is it the `bind` options? I'll make some tests and I'll let you know.

**Comment by babelouest** [comment]
Hello @zandbelt , I'm getting closer!

I have changed the `http_server_spawn` port number to 8080 and now almost all architectures are passing the tests on Debian CI!

I have one new issue with the [armhf arch](https://buildd.debian.org/status/fetch.php?pkg=liboauth2&arch=armhf&ver=1.4.4.1-3&stamp=1650114997&raw=0) which fails at a new place though:

```
test/check_cache.c:87:F:core:test_cache_file:0: Assertion 'rc == 1' failed: rc == 0, 1 == 1
```

The test fails at the following line:
```C
rc = oauth2_cache_set(_log, c, "piet", NULL, 0);
ck_assert_int_eq(rc, true);
```

**Comment by zandbelt** [comment]
I see the following in the log:

> [src/cache/file.c:479:oauth2_cache_file_set:DBG] enter
[src/cache/file.c:379:_oauth2_cache_files_clean:DBG] start cleaning cycle
[src/cache/file.c:431:_oauth2_cache_files_clean:DBG] cache entry (oauth2-cache-piet) expired, removing file "/tmp/oauth2-cache-piet")
[src/cache/file.c:224:_oauth2_cache_file_remove:ERR] could not delete cache file "/tmp/oauth2-cache-piet" (No such file or directory)
[src/cache/file.c:535:oauth2_cache_file_set:DBG] leave: 0
[src/cache.c:431:oauth2_cache_set:ERR] leave: could NOT store: piet

and I'm pretty sure it is a timing issue or race condition similar to the one I fixed only recently in mod_auth_openidc; I will look in to it soon and report back

**Comment by zandbelt** [comment]
can you try https://github.com/zmartzone/liboauth2/releases/tag/v1.4.4.2 ?

**Comment by babelouest** [comment]
Looks like [it works](https://buildd.debian.org/status/package.php?p=liboauth2&suite=experimental)!

I'll upload to unstable in the next days, thanks!
