### ISSUE TITLE
Missing include paths

### ISSUE THREAD

**Issue by may-day** [zmartzone/liboauth2#35]
Hi,

when compiling `liboauth2`  it cannot find `<cjose/cjose.h>` (my `PKG_CONFIG_PATH` points to the right location).
I think the `AM_CPPFLAGS` var in `Makefile.am` should also contain `@CJOSE_CFLAGS@` (and `@CURL_CFLAGS@`).

**Comment by zandbelt** [comment]
that should be covered by https://github.com/zmartzone/liboauth2/blob/master/Makefile.am#L46 ; which file fails to compile?

**Comment by may-day** [comment]
Ah, it errors out when compiling cache.c:
```
-cache.Tpo -c src/cache.c  -fPIC -DPIC -o src/.libs/liboauth2_cache_la-cache.o
In file included from src/cache.c:30:
./include/oauth2/jose.h:25:10: fatal error: cjose/cjose.h: No such file or directory
   25 | #include <cjose/cjose.h>
      |          ^~~~~~~~~~~~~~~
```
So `liboauth2_cache_la_CPPFLAGS` needs the additional flags
