### ISSUE TITLE
[RefactoringRequest] oauth2_token_verify method renaming

### ISSUE THREAD

**Issue by SychevIgor** [zmartzone/liboauth2#4]
First of all - Thank you for all what you are doing.

We are debugging mod_oauth2 module and faced with misunderstanding. 
Initially, we expected that oauth2_token_verify will validate jwt token, but instead code verifying only json compatibility. Agree, name don't include jwt, but it's what we assumed. 
Maybe you can modify the name to reflect json validation in a naming?

**Comment by zandbelt** [comment]
actually `oauth2_token_verify ` does verify JWTs: a token is not always a JWT, but if it is you'd use something like:
 ```
OAuth2TokenVerify jwks_uri <jwks_uri>`
```
depending on where you get the key material from

**Comment by SychevIgor** [comment]
We are talking about the same method? This method don't know anything about JWT validation (for me JWT validation is - verification of signature) 
![image](https://user-images.githubusercontent.com/578954/64848380-bc1c2b80-d619-11e9-89df-4864de9bf709.png)

Also -I'm not wanna write code, we are debugging why we our Azure AD application account can't authorize.

**Comment by zandbelt** [comment]
`ptr->callback` calls into https://github.com/zmartzone/liboauth2/blob/master/src/jose.c#L1109`when configured for JWT based access tokens

**Comment by SychevIgor** [comment]
thank you for an explanation.
