### ISSUE TITLE
how to introspect URL with GET?

### ISSUE THREAD

**Issue by walidbenhammouda** [zmartzone/liboauth2#6]
Hello,
I have ONLY one introspect URL that is accepting Authorization Bearer via GET. however I am seeing in http.c that is setting POST (when data is always not NULL as it has the token) which not compatible to my introspect URL specs.

![image](https://user-images.githubusercontent.com/3730730/67545006-8c0a8280-f6c5-11e9-9754-a6be5532835e.png)

how can I force the OAuth2 to do GET instead? it seems not possible from the source code unlike the older version.

Appreciate your help again.

**Comment by zandbelt** [comment]
This is a non-standard-compliant feature request. I would advise you to have the provider change its implementation to be spec compliant.

**Comment by walidbenhammouda** [comment]
do you have please the spec for this plugin, a draft should be fine that lists all the features and options so I know what discussion to conduct with the token provider support?

I have an introspect that uses POST, but it accepts only token in the Body / x-www-form (otherwise HTTP 400 bad request). it there a way to tell the plugin to use the body instead of form-dat?

Thanks

**Comment by walidbenhammouda** [comment]
I see.

so based on that RFC7662, I an wondering at what level is the regression between 2.3 and 2.4 when doing the same steps and config.
below is what I tested so far. 

#2.3 working OK
OIDCOAuthIntrospectionEndpoint https://url/api
OIDCOAuthIntrospectionEndpointMethod    POST
OIDCOAuthIntrospectionEndpointAuth none
OIDCOAuthSSLValidateServer    Off
OIDCOAuthIntrospectionTokenParamName    access_token
OIDCOAuthAcceptTokenAs header
OIDCOAuthRemoteUserClaim login_name
		
#2.4 Not working Error 400 

OAuth2TokenVerify introspect https://url/api
OAuth2AcceptTokenIn header name=Authorization&type=Bearer
OAuth2TargetPass  login_name

what is missing in the 2.4 config that makes the call fails to 400 ?

Thanks again

**Comment by zandbelt** [comment]
again, the parameter name for the token is standardized and is `token`, not `access_token`, see: https://tools.ietf.org/html/rfc7662#section-2.1

**Comment by walidbenhammouda** [comment]
my bad I looked to the wrong RFC I will follow-up that point with the provider's team.
And how about the expiration it seems not working. I set 20 minutes as an expiration but the introspect still accepting the token after that.

thanks

**Comment by zandbelt** [comment]
closing this as this project will not support non-standardized introspection protocols
